/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary-fixed-dim": "#adc6ff",
        "on-tertiary-container": "#fffbff",
        "primary-container": "#0070eb",
        "on-tertiary": "#ffffff",
        "surface": "#faf9fe",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f1f0f5",
        "secondary-container": "#6664e4",
        "inverse-primary": "#adc6ff",
        "on-tertiary-fixed-variant": "#7c2e00",
        "outline-variant": "#c1c6d7",
        "surface-dim": "#dad9df",
        "secondary": "#4c4aca",
        "on-tertiary-fixed": "#351000",
        "on-secondary-fixed": "#0c006a",
        "on-surface": "#1a1b1f",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-container-high": "#e9e7ed",
        "primary": "#0058bc",
        "on-primary-container": "#fefcff",
        "secondary-fixed": "#e2dfff",
        "surface-tint": "#005bc1",
        "on-primary-fixed-variant": "#004493",
        "on-surface-variant": "#414755",
        "surface-container": "#eeedf3",
        "surface-bright": "#faf9fe",
        "primary-fixed": "#d8e2ff",
        "surface-variant": "#e3e2e7",
        "on-secondary-container": "#fffbff",
        "surface-container-low": "#f4f3f8",
        "tertiary-container": "#c64f00",
        "surface-container-highest": "#e3e2e7",
        "on-background": "#1a1b1f",
        "on-primary-fixed": "#001a41",
        "on-secondary-fixed-variant": "#3631b4",
        "tertiary-fixed": "#ffdbcc",
        "on-primary": "#ffffff",
        "background": "#faf9fe",
        "outline": "#717786",
        "tertiary-fixed-dim": "#ffb595",
        "tertiary": "#9e3d00",
        "secondary-fixed-dim": "#c2c1ff",
        "inverse-surface": "#2f3034",
        "error-container": "#ffdad6"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xs": "4px",
        "margin-desktop": "40px",
        "max-width": "1200px",
        "unit": "4px",
        "lg": "24px",
        "md": "16px",
        "xl": "32px",
        "gutter": "20px",
        "sm": "8px"
      },
      "fontFamily": {
        "body-lg": ["Inter"],
        "title-md": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "headline-lg": ["Inter"]
      },
      "fontSize": {
        "body-lg": ["17px", {"lineHeight": "24px", "letterSpacing": "-0.011em", "fontWeight": "400"}],
        "title-md": ["19px", {"lineHeight": "24px", "letterSpacing": "-0.015em", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.019em", "fontWeight": "600"}],
        "label-sm": ["11px", {"lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "label-md": ["13px", {"lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "500"}],
        "body-md": ["15px", {"lineHeight": "20px", "letterSpacing": "-0.009em", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.022em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.019em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.021em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
}
